Doc: Add liquid examples
3scale/APIcast pull request #1300
Opened 2021-08-20 11:08 UTC by eloycoto

Signed-off-by: Eloy Coto <eloy.coto@acalustra.com>

2021-08-30 09:55 UTC, porueesq commented on doc/liquid_conditions.md
> +When using liquid, a lot of things can be achieved, and here are some examples
You can use Liquid to configure conditions applicable across multiple policies to <insert_purpose>

Some questions to help you:
* What's the benefit of using Liquid to configure conditions across multiple policies?
* Are there any prerequisites to use these examples?
* Are there any limitations with these examples? For instance, can these examples be used in a production environment?

2021-08-30 09:57 UTC, porueesq commented on doc/liquid_conditions.md
> +Condition pass if header 'Backend' is sent and it's staging
```suggestion
Condition passes if the  'Backend' header is sent and it's staging
```

Questions:
a. Who/What sends the  'Backend' header ?
b. What does `staging` refer to?

2021-08-30 09:58 UTC, porueesq commented on doc/liquid_conditions.md
> +If want to test when the header is not present, the condition will be like this:
```suggestion
If you want to test when the `Backend` header is not present, the condition is as follows:
```

2021-08-30 09:59 UTC, porueesq commented on doc/liquid_conditions.md
> +These are harder, by default, all the values on liquid are strings, so we need
```suggestion
Numeric operations require additional steps. By default, all the values on liquid are strings, so you need
```

2021-08-30 09:59 UTC, porueesq commented on doc/liquid_conditions.md
> +to get any integer before do any operation. We can use `minus` or `plus`
```suggestion
to get any integer before do any operation. Use `minus` or `plus`
```

2021-08-30 10:00 UTC, porueesq commented on doc/liquid_conditions.md
> +filters using 0, and do something like this:
```suggestion
filters along with `0` (zero), and apply the following configuration:
```

2021-08-30 10:04 UTC, porueesq commented on doc/liquid_conditions.md
> +## Another examples:
```suggestion
## Additional examples:
```

2021-08-30 10:05 UTC, porueesq requested changes
Some questions and suggestions

2022-05-12 20:17 UTC, eguzki approved these changes

2022-05-12 20:18 UTC, merged