[WIP] THREESCALE-8000 + THREESCALE-8007 (clear context policy)
3scale/APIcast pull request #1328
Opened 2022-02-24 15:29 UTC by samugi

This PR adds compatibility with [this OpenResty change](https://github.com/openresty/lua-nginx-module/pull/1514/files). 
It takes care of clearing the local context at the beginning of every separate request.

We use the context to determine routing to Products (when APICAST_PATH_ROUTING is enabled) or to Backends (when using APIaaP). Both those routing scenarios can be affected by the bug when connections are reused (see also [KCS1](https://access.redhat.com/solutions/6707511) and [KCS2](https://access.redhat.com/solutions/6749581))

2022-02-25 17:25 UTC, eloycoto commented
umm, maybe I do not understand the full context here, but I do not think that context should be clear at all. Maybe what we should do it drop support of SSL_context on ssl_certificate phase and keep as was before the change.

2022-02-25 18:06 UTC, samugi commented
> umm, maybe I do not understand the full context here, but I do not think that context should be clear at all. Maybe what we should do it drop support of SSL_context on ssl_certificate phase and keep as was before the change.

The idea is based on the problem being that our code does not expect the context to be shared across different requests but rather for it to be scoped by request (this is true at least for the path routing algorithm and the routing policy). 

The option we are exploring here would address this by resetting the context at the beginning of each request (which is what this policy does), that should be equivalent to what happens when the ssl_certificate phase is not executed at all (i.e. there will be nothing in the `current` context when the first policy executes for a certain request). 

Another option (which I believe is what you are suggesting?) would be to avoid interacting with the context in all the ssl_certificate phases across all policies but that seemed more of a breaking change due to [this](https://github.com/3scale/APIcast/blob/f018994f1ca447e528636527a31c4683aea9c04e/gateway/src/apicast/policy/find_service/find_service.lua#L62-L63) and [this](https://github.com/3scale/APIcast/blob/f018994f1ca447e528636527a31c4683aea9c04e/gateway/src/apicast/policy/load_configuration/load_configuration.lua#L42-L53) for example.

2022-02-27 11:42 UTC, samugi commented
After some more testing I found another problem **with the same root cause**: THREESCALE-8252.

@eloycoto I just committed a slightly modified version of the policy that I believe to be a safer option: it resets the current context at the *end* of every request (in the log phase of the last policy in the chain) rather than at the beginning. This way the reset of the context will happen when no other policy will need to access to it, and so it will be reinitialized correctly in the `executor` on the next request. If in the future we will want some parts of the context to be shared through different requests it will be easy to tune the policy accordingly to leave those. 

This commit also takes care of THREESCALE-8252 because the original_request will be populated as normal [here](https://github.com/3scale/APIcast/blob/f018994f1ca447e528636527a31c4683aea9c04e/gateway/src/apicast/executor.lua#L41-L64).

I added integration tests to confirm all 3 issues are covered.

2022-02-27 20:28 UTC, eloycoto commented
umm, I do not think that will work @samugi , mainly because requests can be concurrent, and that can be a problem. SSL context should be disabled.

2022-02-27 21:41 UTC, samugi commented
> umm, I do not think that will work @samugi , mainly because requests can be concurrent, and that can be a problem. SSL context should be disabled.

@eloycoto does that mean concurrent requests could share the same context? I thought that wouldn't be possible especially since we are relying on `context.current` for things like routing and some objects in particular (e.g. `context.current.service`) require to be scoped by request but perhaps I'm missing something. 

In what scenario would properties of `context.current` be reused after a policy chain completes its execution for a certain request? Is there any test that you would be expecting to fail?

Also I thought we were relying on the SSL context for a few things now, am I wrong? I thought this to be the case for the TLS policy for example, which requires the service to have [already been determined](https://github.com/3scale/APIcast/blob/f018994f1ca447e528636527a31c4683aea9c04e/gateway/src/apicast/policy/find_service/find_service.lua#L62-L63) during the ssl_certificate phase. I'll double check though, maybe we are storing the service in the context for other reasons there, I haven't looked into that yet. 

Thanks for your feedback

2022-02-28 15:58 UTC, eloycoto commented
SSL certificate only happens once, on ssl_handshake, and from there many more requests to come. 

So, no set context on ssl_certificate and initialize on `rewrite` phase where the service will be in there. 

I mean, if you change this line should be ok: 

https://github.com/3scale/APIcast/blob/master/gateway/src/apicast/policy/find_service/find_service.lua#L62

2022-03-01 09:44 UTC, kevprice83 commented
@eloycoto I already suggested the same and @samugi gave some reasoning why that wouldn't be a good idea. I forget exactly what that was now but I suspect it is something related to the fact that removing the context in the `ssl_certificate_phase` could end up breaking the new [behaviour introduced in OpenResty](https://github.com/openresty/lua-nginx-module/pull/1514/files) that @samugi mentioned at the top of this PR. My thinking here was that we never needed that behaviour previously and therefore we would not need it now and given that we have a very specific use case regarding the context in APIcast probably we can just unset it during that phase and initialise it in the next (rewrite) phase.

@samugi could you remind why else you thought that was a bad idea because I cannot remember now. I think I remember you preferred to keep the behaviour introduced in OpenResty and only improve how we manage the management of the context object right?

I'd say in general that's the best approach and keep compatibility with as much OpenResty features as possible but I also think this was a breaking change in OpenResty that they didn't handle very well and as a result we have to cope with this somehow.

One advantage to Samuele's proposal I'd say is that this behaviour could be configurable and so in future if we need to _"enable"_ that OpenResty _"feature"_ again then skipping or disabling the policy would be easy don't you think @eloycoto ?

2022-03-01 16:19 UTC, samugi commented
I discussed this with @kevprice83 this morning, here is a recap of our discussion:

We believe we have 3 ways of addressing this problem:
1. The current proposal here (clearing the context in the log phase of the last policy in the chain).

    Pros:

      - Safe because it clears the context at the end of the policy chain when no other policy could need to access it
      - Modular: can be reverted or altered by removing / modifying the policy 
      - Allows to take advantage of [the OpenResty change](https://github.com/openresty/lua-nginx-module/pull/1514) should we need to share the context from ssl_* phases in the future
    
    Cons:

      - We would execute some code (the claring context part) even when it's not strictly necessary (e.g. in the event the ssl_certificate phase was never executed)
2. Clearing the context right after [these lines](https://github.com/3scale/APIcast/blob/f018994f1ca447e528636527a31c4683aea9c04e/gateway/src/apicast/policy/find_service/find_service.lua#L62-L63)

    Pros:

      - The change would only apply when strictly necessary, during the `ssl_certificate` phase

    Cons:

      - Potentially in the future we might want to access the context of the `ssl_certificate` phase in a policy that comes after `find_service` and that would be problematic because:
          - the context would have been cleared already
          - any change in the context executed **after** `find_service` would then be shared with multiple requests (potentially producing the same issue we see now)
      - Does not allow to take advantage of [the OpenResty change](https://github.com/openresty/lua-nginx-module/pull/1514) should we need to share the context from ssl_ phases in the future
3. Clearing the context in the `clear_context` policy, from the last position in the policy chain, but in the `ssl_certificate` phase (rather than the `log` phase)

    Pros:

      - The change would only apply when strictly necessary, during the `ssl_certificate` phase
      - Modular: can be reverted or altered by removing / modifying the policy 

    Cons:
      - Does not allow to take advantage of [the OpenResty change](https://github.com/openresty/lua-nginx-module/pull/1514) should we need to share the context from ssl_ phases in the future

What would you think of the proposals above @eloycoto ?

Also one more thing just to clarify a point from the previous comments: when you said "SSL context should be disabled." and "So, no set context on ssl_certificate and initialize on rewrite phase where the service will be in there.", did you in fact mean to suggest the context should be cleared during the `ssl_certificate` phase or do you actually meant that we should completely stop accessing / sharing a context in the `ssl_certificate` phase of **any** policy?

2022-03-01 16:43 UTC, kevprice83 commented
Would be good to get some feedback from @sergioifg94 & @eguzki on that last comment maybe?

2022-03-01 18:13 UTC, kevprice83 requested changes
I think it would be useful to run the test requests concurrently to see the outcome. I'd expect one of them to fail in which case that would make it clearer that we then **must** clear the context at the end of the `ssl_certificate_phase` in the last policy in the policy chain. Other than that I think doing this as a separate policy is a good approach.

2022-03-04 10:04 UTC, samugi commented on t/apicast-policy-routing.t
> +[error]
done

2022-03-04 10:05 UTC, samugi commented on t/apicast-policy-routing.t
> +Routing must work as expected to the right backend
done

2022-03-04 10:05 UTC, samugi commented on t/apicast-policy-routing.t
> +  --check for incorrect routing THREESCALE-8007:
done

2022-03-04 10:58 UTC, samugi commented
> I think it would be useful to run the test requests concurrently to see the outcome. I'd expect one of them to fail in which case that would make it clearer that we then **must** clear the context at the end of the `ssl_certificate_phase` in the last policy in the policy chain. Other than that I think doing this as a separate policy is a good approach. Maybe using the [concurrent library here](https://github.com/3scale/APIcast/tree/e7f6ebbf15d1b053283f0d77ae7176e1c7bfcb44/gateway/src/resty/concurrent)?

for this one I used [request_pipeline](https://github.com/ledgetech/lua-resty-http/tree/41b2e822ce5c19f64e293b7dc2d5d244e511615d#request_pipeline). I then verified that in fact the tests fail when clearing the context in the log phase (which wouldn't handle concurrent requests) and pass when the context is cleared at the end of the `ssl_certificate` phase (as we expected).

2022-03-04 17:00 UTC, kevprice83 approved these changes
Based on our discussions and previous feedback this looks good to me!

2022-03-05 07:47 UTC, eloycoto commented
yeah, make sense that ssl_certificate, because all connections do the ssl_handshake before it. I have another thing in mind here, use with tls_termination policy too, because clear the context is ssl_certificate happens before ssl_handshake on tls_termination. 

Please raise this issue to the QE team, @DavidRajnoha  is no longer working on this, but I'm sure that @mganisin can make a test plan for this. But overall, it's testing that two services in the same APICAST landed in the right place.

2022-03-08 13:17 UTC, eguzki approved these changes

2022-03-15 09:06 UTC, merged

2022-04-19 20:30 UTC, samugi commented
there seems to be a problem when the tls policy is in the policy chain and executes [this code](https://github.com/3scale/APIcast/blob/master/gateway/src/apicast/policy/tls/tls.lua#L194) which exits and does not permit the clearing context code to be executed.