Including the env var LARGE_CLIENT_HEADER_BUFFERS
3scale/APIcast pull request #1429
Opened 2023-11-20 17:19 UTC by perylemke

Include `LARGE_CLIENT_HEADER_BUFFERS` var to my first contribution on APICast.

2023-11-20 17:50 UTC, dfennessy commented on doc/parameters.md
> +Sets the maximum number and size of buffers used for reading large client request header. A request line cannot exceed the size of one buffer, or the 414 (Request-URI Too Large) error is returned to
```suggestion
This environment variable sets the maximum number and size of buffers for reading large client request headers. A request line cannot exceed the size of one buffer, or the client receives a 414 (Request-URI Too Large) error. A request header field cannot exceed the size of one buffer or the client receives a 400 (Bad Request) error. Buffers are allocated only when necessary, with a default size of [8K](http://nginx.org/en/docs/http/ngx_http_core_module.html#large_client_header_buffers) bytes. After processing a request, if the connection transitions into the keep-alive state, these buffers are released.
```

2023-11-20 17:51 UTC, dfennessy reviewed
Some minor suggestions to the paragraph.

2023-12-20 06:18 UTC, tkan145 requested changes
The current code only reads the env var, you will need to also render the value to the `apicast.conf.liquid` file

For example

```diff
diff --git a/gateway/http.d/apicast.conf.liquid b/gateway/http.d/apicast.conf.liquid
index 93d60775..3f1df64c 100644
--- a/gateway/http.d/apicast.conf.liquid
+++ b/gateway/http.d/apicast.conf.liquid
@@ -134,6 +134,10 @@ server {
 
   {% include "http.d/ssl.conf" %}
 
+  {% if large_client_header_buffers != empty %}
+  large_client_header_buffers {{large_client_header_buffers}};
+  {% endif %}
+
   {% for file in "apicast.d/*.conf" | filesystem %}
     {% include file %}
   {% endfor %}
```

2024-01-16 17:05 UTC, eguzki commented
any progress on this issue?

2024-02-13 10:11 UTC, eguzki commented
Superseded by https://github.com/3scale/APIcast/pull/1446

2024-02-13 10:11 UTC, closed without merging