Add support to set large_client_header_buffers directive
3scale/APIcast pull request #1446
Opened 2024-02-08 07:00 UTC by tkan145

### What

Fixes: https://issues.redhat.com/browse/THREESCALE-10582

### Verification Steps

* Creat a `apicast-config.json` file with the following content

```
{                                                      
  "services": [                                        
    {                                                  
      "id": "1",                                       
      "backend_version": "1",                          
      "proxy": {                                       
        "hosts": ["one"],                              
        "api_backend": "https://echo-api.3scale.net:443",
        "backend": {                                   
          "endpoint": "http://127.0.0.1:8081",         
          "host": "backend"                            
        },                                             
        "policy_chain": [                                                               
          { "name": "apicast.policy.apicast" }                                            
        ],                                             
        "proxy_rules": [                               
          {                                            
            "http_method": "GET",                      
            "pattern": "/",                            
            "metric_system_name": "hits",              
            "delta": 1,                                
            "parameters": [],                          
            "querystring_parameters": {}               
          }                                            
        ]                                              
      }                                                
    }                                                  
  ]                                                    
}                                                      

```

* Checkout this branch and start dev environment
```
make development
make dependencies
```
* Run apicast locally
```
THREESCALE_DEPLOYMENT_ENV=staging APICAST_LOG_LEVEL=debug APICAST_WORKER=1 APICAST_CONFIGURATION_LOADER=lazy APICAST_CONFIGURATION_CACHE=0 THREESCALE_CONFIG_FILE=apicast-config.json ./bin/apicast
```

* Capture apicast IP
```
APICAST_IP=$(docker inspect apicast_build_0-development-1 | yq e -P '.[0].NetworkSettings.Networks.apicast_build_0_default.IPAddress' -)
```
* Generate big header
```
LARGE_HEADER=$(for i in {1..1024}; do echo -n 'ABCDEFGH'; done)
```
* Send request with big header
```
curl -i -k -H "Host: one" -H "Accept: application/json" -H "Large-Header: ${LARGE_HEADER}" "http://${APICAST_IP}:8080/?user_key="
```

The response should be HTTP/1.1 400 Bad Request

```
HTTP/1.1 400 Bad Request                                          
Server: openresty                                                 
Date: Thu, 08 Feb 2024 06:49:26 GMT                               
Content-Type: text/html                                           
Content-Length: 230                                               
Connection: close                                                 
                                                                  
<html>                                                            
<head><title>400 Request Header Or Cookie Too Large</title></head>
<body>                                                            
<center><h1>400 Bad Request</h1></center>                         
<center>Request Header Or Cookie Too Large</center>               
<hr><center>openresty</center>                                    
</body>                                                           
</html>                                                           
```

* Stop the gateway
```
CTRL-C
```

* Start gateway again with `APICAST_LARGE_CLIENT_HEADER_BUFFERS=4 12k`
```
THREESCALE_DEPLOYMENT_ENV=staging APICAST_LOG_LEVEL=debug APICAST_WORKER=1 APICAST_CONFIGURATION_LOADER=lazy APICAST_CONFIGURATION_CACHE=0 THREESCALE_CONFIG_FILE=apicast-config.json APICAST_LARGE_CLIENT_HEADER_BUFFERS="4 12k" ./bin/apicast
```

* Send another request
```
curl -i -k -H "Host: one" -H "Accept: application/json" -H "Large-Header: ${LARGE_HEADER}" "http://${APICAST_IP}:8080/?user_key="
```

The response should be HTTP/1.1 200 OK

2024-02-08 15:03 UTC, eguzki reviewed
Looking good.

2024-02-09 06:22 UTC, tkan145 commented
I kindly requested review from @3scale/documentation team. 

For some reason the test keeps failing in this PR :disappointed: , hopefully after I address the feedback from the docs team and make a new commit the test will work

2024-02-09 09:32 UTC, dfennessy commented on CHANGELOG.md
> +- Added `APICAST_CLIENT_REQUEST_HEADER_BUFFERS` variable that allows to configure nginx `client_request_header_buffers` directive [PR #1446](https://github.com/3scale/APIcast/pull/1446), [THREESCALE-
```suggestion
- Added `APICAST_CLIENT_REQUEST_HEADER_BUFFERS` variable to allow configuration of the NGINX `client_request_header_buffers` directive: [PR #1446](https://github.com/3scale/APIcast/pull/1446), [THREESCALE-10164](https://issues.redhat.com/browse/THREESCALE-10164)
```

2024-02-09 10:41 UTC, dfennessy requested changes
I've added a suggestion.

2024-02-13 09:57 UTC, eguzki requested changes
Verification steps working like a charm

Some nitpicking and ready to merge.

2024-02-13 09:57 UTC, eguzki commented on t/large-client-header-buffers.t
> +=== TEST 1: large header (the header exceed exceed the size of one buffer)
`exceed exceed` :eyes:

2024-02-13 09:57 UTC, eguzki commented on t/large-client-header-buffers.t
> +  client_header_buffer_size 10;
this is needed? why?

2024-02-13 12:23 UTC, tkan145 commented on t/large-client-header-buffers.t
> +=== TEST 1: large header (the header exceed exceed the size of one buffer)
good catch

2024-02-14 09:21 UTC, eguzki reviewed
LGTM but there are new conflicts (in CHANGELOG)

2024-02-19 04:58 UTC, tkan145 commented on t/large-client-header-buffers.t
> +  client_header_buffer_size 10;
fixed

2024-02-19 04:58 UTC, tkan145 commented on t/large-client-header-buffers.t
> +=== TEST 1: large header (the header exceed exceed the size of one buffer)
fixed

2024-02-19 04:59 UTC, tkan145 commented
Conflict resolved

2024-02-19 12:23 UTC, eguzki approved these changes

2024-02-19 12:23 UTC, eguzki commented
@dfennessy your approval is needed as you requested changes

2024-02-19 13:00 UTC, dfennessy approved these changes
/lgtm

2024-02-20 00:30 UTC, merged